'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Save, ChevronDown, ChevronUp, Plus, AlertTriangle, CheckCircle } from 'lucide-react'
import { DEMO_JD_WEIGHTS, SECTION_LABELS } from '@/data/static-data'
import toast from 'react-hot-toast'

export default function JdWeightsPage() {
  const router = useRouter()
  const [weights, setWeights] = useState(DEMO_JD_WEIGHTS)
  const [expandedSections, setExpandedSections] = useState({ relevant_experience: true })
  const [confirmed, setConfirmed] = useState(false)

  const totalWeight = Object.values(weights.scoring).reduce((sum, s) => sum + s.weight, 0) + weights.salary.weight
  const isValid = Math.abs(totalWeight - 100) < 0.1

  const toggleSection = (key) => setExpandedSections(prev => ({ ...prev, [key]: !prev[key] }))

  const updateWeight = (section, value) => {
    setWeights(prev => ({
      ...prev,
      scoring: { ...prev.scoring, [section]: { ...prev.scoring[section], weight: parseFloat(value) } },
    }))
  }

  const updateCriteria = (section, key, value) => {
    setWeights(prev => ({
      ...prev,
      scoring: {
        ...prev.scoring,
        [section]: {
          ...prev.scoring[section],
          criteria: { ...prev.scoring[section].criteria, [key]: parseFloat(value) },
        },
      },
    }))
  }

  const handleConfirm = () => {
    if (!isValid) { toast.error('Weights must sum to 100!'); return }
    if (!confirmed) {
      setConfirmed(true)
      toast('Any further changes?', { icon: '🤔', duration: 3000 })
      return
    }
    toast.success('Weights saved! Returning to platform...')
    setTimeout(() => router.push('/platform'), 1000)
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl sm:text-3xl font-bold text-white flex items-center gap-3">
          <span className="text-3xl">⚖️</span> JD Weight Assignment
        </h1>
        <p className="text-slate-400 text-sm mt-1">Review and adjust scoring weights generated by LLM</p>
      </div>

      {/* Job Info */}
      <div className="glass-card p-6">
        <h2 className="text-lg font-semibold text-white mb-4">📋 Job Information</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {[
            { label: 'Job Title', value: weights.job_title },
            { label: 'Experience', value: weights.experience },
            { label: 'Qualification', value: weights.qualification },
            { label: 'Location', value: weights.location },
            { label: 'Position', value: weights.position },
            { label: 'Employment', value: weights.employment_type },
          ].map(f => (
            <div key={f.label}>
              <label className="text-xs text-slate-500 mb-1 block">{f.label}</label>
              <input defaultValue={f.value} className="w-full px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-sm text-white focus:ring-2 focus:ring-raiya-500 focus:outline-none" />
            </div>
          ))}
        </div>
      </div>

      {/* Weight Total Bar */}
      <div className={`glass-card p-4 flex items-center justify-between ${isValid ? 'border-green-500/30' : 'border-amber-500/30'}`}>
        <div className="flex items-center gap-3">
          {isValid ? <CheckCircle className="w-5 h-5 text-green-400" /> : <AlertTriangle className="w-5 h-5 text-amber-400" />}
          <span className="text-sm font-medium text-white">Total Weight</span>
        </div>
        <div className={`text-2xl font-bold ${isValid ? 'text-green-400' : totalWeight > 100 ? 'text-red-400' : 'text-amber-400'}`}>
          {totalWeight.toFixed(1)} <span className="text-sm text-slate-400">/ 100</span>
        </div>
      </div>

      {/* Scoring Sections */}
      {Object.entries(weights.scoring).map(([key, section]) => {
        const isExpanded = expandedSections[key]
        const label = SECTION_LABELS[key] || key
        return (
          <div key={key} className="glass-card overflow-hidden">
            <button onClick={() => toggleSection(key)} className="w-full flex items-center justify-between p-4 hover:bg-white/5 transition-colors">
              <div className="flex items-center gap-3">
                <span className="text-base">{label}</span>
                <span className="text-xs px-2 py-0.5 rounded-full bg-raiya-500/20 text-raiya-300">w: {section.weight}</span>
              </div>
              {isExpanded ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
            </button>
            {isExpanded && (
              <div className="px-4 pb-4 space-y-3 border-t border-white/5 pt-3">
                <div>
                  <label className="text-xs text-slate-500">Section Weight</label>
                  <input type="range" min="0" max="50" step="0.5" value={section.weight} onChange={(e) => updateWeight(key, e.target.value)}
                    className="w-full h-2 rounded-full appearance-none bg-white/10 accent-raiya-500 cursor-pointer" />
                  <div className="flex justify-between text-xs text-slate-500 mt-1"><span>0</span><span className="font-bold text-raiya-300">{section.weight}</span><span>50</span></div>
                </div>
                <div className="space-y-2">
                  <p className="text-xs text-slate-500 font-medium">Criteria Scores (0-100)</p>
                  {Object.entries(section.criteria).map(([cKey, cVal]) => (
                    <div key={cKey} className="flex items-center gap-3">
                      <span className="text-xs text-slate-400 w-40 truncate">{cKey}</span>
                      <input type="range" min="0" max="100" value={cVal} onChange={(e) => updateCriteria(key, cKey, e.target.value)}
                        className="flex-1 h-1.5 rounded-full appearance-none bg-white/10 accent-raiya-400 cursor-pointer" />
                      <span className="text-xs text-white w-8 text-right font-mono">{cVal}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )
      })}

      {/* Salary Section */}
      <div className="glass-card p-4">
        <h3 className="text-base font-medium text-white mb-3">💰 Salary (w: {weights.salary.weight})</h3>
        <input type="range" min="0" max="20" step="0.5" value={weights.salary.weight}
          onChange={(e) => setWeights(prev => ({ ...prev, salary: { ...prev.salary, weight: parseFloat(e.target.value) } }))}
          className="w-full h-2 rounded-full appearance-none bg-white/10 accent-amber-400 cursor-pointer" />
      </div>

      {/* Confirm Buttons */}
      <div className="flex flex-col sm:flex-row gap-3">
        <button onClick={handleConfirm} disabled={!isValid}
          className={`flex-1 py-3 rounded-xl font-semibold flex items-center justify-center gap-2 transition-all shadow-lg ${confirmed
            ? 'bg-gradient-to-r from-green-600 to-green-500 shadow-green-500/20 text-white'
            : 'bg-gradient-to-r from-raiya-600 to-raiya-500 shadow-raiya-500/20 text-white'
          } disabled:opacity-40`}>
          <Save className="w-5 h-5" />
          {confirmed ? 'CONFIRM — NO FURTHER CHANGES' : 'Save Weights & Continue'}
        </button>
      </div>
    </div>
  )
}
